//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploDatabaseFirst.ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Artigos()
        {
            this.Palestras = new HashSet<Palestras>();
        }
    
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Abstract { get; set; }
        public int AutorId { get; set; }
        public int PalestranteId { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
        public virtual Pessoas Pessoas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Palestras> Palestras { get; set; }
    }
}
