//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploDatabaseFirst.ConsoleApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConferenciaCientificaEntities : DbContext
    {
        public ConferenciaCientificaEntities()
            : base("name=ConferenciaCientificaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artigos> Artigos { get; set; }
        public virtual DbSet<Palestras> Palestras { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
    }
}
