//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExemploDatabaseFirst.ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palestras
    {
        public int Id { get; set; }
        public int AutorId { get; set; }
        public int ArtigoId { get; set; }
        public System.DateTime DataEHora { get; set; }
    
        public virtual Artigos Artigos { get; set; }
        public virtual Pessoas Pessoas { get; set; }
    }
}
